### PR TITLE
Support for Primo VE, with plus new Integration test matcher

### PR DESCRIPTION
**Pull request by mberkowski**
Supports URL param changes for Primo VE (Jul 18, 2023)
- New integration test matcher for result count in tag
```
<prm-search-result-page-range ng-if="$ctrl.enableTopPagination" .....>...</prm-search-result-page-range>
```
- Removes several obsolete Primo scopes, closing a handful of open issues

### Running Integration tests on this before Primo VE release
You must modify /etc/hosts to point a domain such as `primoumn.hosted.exlibris.com` at the correct IP, then _temporarily_ change all references from `primo.lib.umn.edu` in lib/primo.js & test/primo.js to use that domain name. All tests will pass. Don't forget to revert your change (don't commit) and revert your /etc/hosts.

### CODE REVIEW

**Comment by nihiliad** [comment]
What version of node are you using? I'm having trouble getting the tests to run.  Running `npm install` with node 14.19.0 gives:
```
npm WARN notsup Unsupported engine for playwright@1.36.0: wanted: {"node":">=16"} (current: {"node":"14.19.0","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: playwright@1.36.0
npm WARN notsup Unsupported engine for playwright-core@1.36.0: wanted: {"node":">=16"} (current: {"node":"14.19.0","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: playwright-core@1.36.0
```

Running `npx test/primonews.js` gives:
```
[..................] / rollbackFailedOptional: verb npm-session f6f5f45d7ad4b70b
```

**Comment by mberkowski** [comment]
> What version of node are you using? I'm having trouble getting the tests to run. Running `npm install` with node 14.19.0 gives:

@nihiliad  Looks like mine are running under v18.3.0 but there have been no changes to package.json

Production hosts have v12.18.0

**Comment by gpeterso** [comment]
> Production hosts have v12.18.0

I'm guessing that  prod dependencies are installed with the `--production` flag (default with cap npm plugin), which would skip the playwright dev dependency.

**Comment by nihiliad** [comment]
One of the errors I reported earlier were due to my own operator error. Should have run `npx tape test/primonews.js`. I was missing `tape`.

**Comment by mberkowski** [comment]
We have some node version issues with the current operating environment which only prevent playwright installation. But since the integration tests are validating the search targets rather than these plugins' URL redirect output, I think we can be satisfied that the integration tests do run under later node versions.

What I mean is these integration tests function strictly as a way to flag if one of the search targets changes in a way we need to be aware of. And in that regard we're fine because they can run successfully on node >=16. The integration tests don't need to be able to run from the perspective of the production environment and its node version limits. Am I thinking this correctly?

**Comment by nihiliad** [comment]
Correct as usual, @mberkowski.

**Pull request merged**
